#!/bin/sh

## Dependencies: pipewire kdialog pipewire-alsa pipewire-audio pipewire-jack

## Variables

AUDIO_BUFFER=`kdialog --combobox "Select an audio buffer" "default" "16" "24" "32" "48" "64" "96" "128" "192" "256" "384" "512" "768" "1024" "2048" "4096" "8192"`
AUDIO_SAMPLE_RATE=`kdialog --combobox "Select a samplerate" "default" "44100" "48000" "88200" "96000" "192000"`

## Set audio buffer for pipewire

case $AUDIO_BUFFER in

	default)
		pw-metadata -n settings 0 clock.force-quantum 0
		;;

	16)
		pw-metadata -n settings 0 clock.force-quantum 16
		;;

	24)
		pw-metadata -n settings 0 clock.force-quantum 24
		;;

	32)
		pw-metadata -n settings 0 clock.force-quantum 32
		;;

	48)
		pw-metadata -n settings 0 clock.force-quantum 48
		;;

	64)
		pw-metadata -n settings 0 clock.force-quantum 64
		;;

	96)
		pw-metadata -n settings 0 clock.force-quantum 96
		;;

	128)
		pw-metadata -n settings 0 clock.force-quantum 128
		;;

	192)
		pw-metadata -n settings 0 clock.force-quantum 192
		;;

	256)
		pw-metadata -n settings 0 clock.force-quantum 256
		;;

	384)
		pw-metadata -n settings 0 clock.force-quantum 384
		;;

	512)
		pw-metadata -n settings 0 clock.force-quantum 512
		;;

	768)
		pw-metadata -n settings 0 clock.force-quantum 768
		;;

	1024)
		pw-metadata -n settings 0 clock.force-quantum 1024
		;;

	2048)
		pw-metadata -n settings 0 clock.force-quantum 2048
		;;

	4096)
		pw-metadata -n settings 0 clock.force-quantum 4096
		;;

	8192)
		pw-metadata -n settings 0 clock.force-quantum 8192
		;;

	*)
		unset $AUDIO_BUFFER
		;;

esac

## Set audio samplerate for pipewire

case $AUDIO_SAMPLE_RATE in

	default)
		pw-metadata -n settings 0 clock.force-rate 0
		;;

	44100)
		pw-metadata -n settings 0 clock.force-rate 44100
		;;

	48000)
		pw-metadata -n settings 0 clock.force-rate 48000
		;;

	88200)
		pw-metadata -n settings 0 clock.force-rate 88200
		;;

	96000)
		pw-metadata -n settings 0 clock.force-rate 96000
		;;

	192000)
		pw-metadata -n settings 0 clock.force-rate 192000
		;;

	*)
		unset $AUDIO_SAMPLE_RATE
		;;

esac

## Display a notification

if [[ ! -z "$AUDIO_BUFFER" ]] && [[ ! -z "$AUDIO_SAMPLE_RATE" ]]; then
	kdialog --title "Pipweire settings changed" --passivepopup "Set the pipewire audio buffer to $AUDIO_BUFFER and audio samplerate to $AUDIO_SAMPLE_RATE." 10
fi
