#!/bin/sh

# Global Variables
LIST_GOVERNORS=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors`
EMPTY_CHARACTER_LENGTH=`grep -o " " <<< "$LIST_GOVERNORS" | wc -l`


# CPU Governors
for (( item=1 ; item<=$(( ${EMPTY_CHARACTER_LENGTH} + 1 )) ; item++ ));
do
    CPU_GOVERNORS+=(`echo $LIST_GOVERNORS | cut -d " " -f $(( $item ))`)
done

# GUI Menu
CPU_GOVERNOR_CHOICE=`kdialog --combobox "Choose CPU Frequency Governor" ${CPU_GOVERNORS[@]}`

# Run command
for (( cpu=0; cpu<$(nproc); cpu++ ))
do
    echo "$CPU_GOVERNOR_CHOICE" > /sys/devices/system/cpu/cpu${cpu}/cpufreq/scaling_governor 2>&1 /dev/null
done
